name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          rsync -avz -e "ssh -p $SERVER_PORT" --exclude '.git' ./ $SERVER_USER@$SERVER_HOST:/var/www/your_project_name/

      - name: Install dependencies and start server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /var/www/your_project_name
            npm install
            npm run build  # Use the appropriate build command for your project
            pm2 restart all || pm2 start npm --name "your_project_name" -- start
          EOF
